// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240121010216_seedCategoryTable")]
    partial class seedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("intCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("intCategoryId"));

                    b.Property<int>("intDisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("strCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("intCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            intCategoryId = 1,
                            intDisplayOrder = 1,
                            strCategoryName = "Action"
                        },
                        new
                        {
                            intCategoryId = 2,
                            intDisplayOrder = 2,
                            strCategoryName = "Romance"
                        },
                        new
                        {
                            intCategoryId = 3,
                            intDisplayOrder = 3,
                            strCategoryName = "SciFi"
                        },
                        new
                        {
                            intCategoryId = 4,
                            intDisplayOrder = 4,
                            strCategoryName = "Crime"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
